name: memory_card_match
description: "A fun memory card matching game."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^3.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/background.jpg 
    - assets/back.jpg 
    - assets/ground.jpg 
    # <-- เพิ่ม assets ตรงนี้
