// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV2ACSmS6J890nDYP0cEn2-7V0teMZwaE',
    appId: '1:942481673638:web:ab29893898b3d744e71367',
    messagingSenderId: '942481673638',
    projectId: 'game-d7337',
    authDomain: 'game-d7337.firebaseapp.com',
    storageBucket: 'game-d7337.firebasestorage.app',
    measurementId: 'G-VTDG3PZ85B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABFhNvxv34qDorNBg5AaEIHPeGJuM482w',
    appId: '1:942481673638:android:2836b40cefa4aff5e71367',
    messagingSenderId: '942481673638',
    projectId: 'game-d7337',
    storageBucket: 'game-d7337.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKutRdB8Axhm01KMiaeV05ixjVf9bLf9I',
    appId: '1:942481673638:ios:ea17c19bc07554bee71367',
    messagingSenderId: '942481673638',
    projectId: 'game-d7337',
    storageBucket: 'game-d7337.firebasestorage.app',
    iosBundleId: 'com.example.memoryCardMatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKutRdB8Axhm01KMiaeV05ixjVf9bLf9I',
    appId: '1:942481673638:ios:ea17c19bc07554bee71367',
    messagingSenderId: '942481673638',
    projectId: 'game-d7337',
    storageBucket: 'game-d7337.firebasestorage.app',
    iosBundleId: 'com.example.memoryCardMatch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCV2ACSmS6J890nDYP0cEn2-7V0teMZwaE',
    appId: '1:942481673638:web:ca8463ece25200bfe71367',
    messagingSenderId: '942481673638',
    projectId: 'game-d7337',
    authDomain: 'game-d7337.firebaseapp.com',
    storageBucket: 'game-d7337.firebasestorage.app',
    measurementId: 'G-0SGQ5YGJJZ',
  );
}
